@extends('maitridiagnosticlab/layout')


@section('title','Hematology Laboratory Tests | Maitri Diagnostic Lab')
@section('meta_description','Comprehensive hematology laboratory tests in Ambala using advanced hematoanalyzers. Blood testing and analysis by certified pathologists at Maitri Diagnostic Lab.')
@section('og_image', asset('maitridiagnosticlab/wp-content/uploads/2015/10/Hematology.jpg'))



@section('main')



<div class="head_panel">

    <div 
      style="
          background-image: url({{asset('maitridiagnosticlab/wp-content/uploads/2017/01/Hematology.jpg')}}); 
          height: 113px;
      " 
      class="full_width_photo"
    >


      <div class="hgroup">

        <div class="title diagonal-bgcolor-trans   ">
          <div class="container">
            <h1>Hematology</h1>
          </div>
        </div>

        <div class="subtitle body-bg_section   ">
          <div class="container">   
            <p></p>
          </div>
        </div>

      </div>


    </div>
</div>


<div class="brand-colors"> </div>


<div class="main foo" data-colorset="foo">
<!--    >> START ========================= CONTENT AREA ========================  -->




<section class="sidebar_on padding_top_half"><div class="container"><div class="row">
<!--   START >> ========================= MAIN COLUMN ========================  -->
<div class="col-sm-8 col-md-8 main_col ">
<section class="vc_row wpb_row vc_row-fluid">
    <div class="row">
            <div class="wpb_column vc_column_container col-sm-12 margin_bottom_grid">
                <div class="wpb_wrapper">

  <div class="wpb_text_column wpb_content_element ">
    <div class="wpb_wrapper">
      <ul>
<li>We offer services of routine haematological tests as well as special tests (refer to test menu for details).</li>
<li>We have trained and experienced phlebotomists ensuring a hassle free experience during blood sample collection (correctly labelled samples collected in hospitals are also accepted in the lab).</li>
<li>The tests are performed by trained and experienced technicians under active supervision of pathologists and all values generated by automated hematoanalyzers are cross checked by the pathologists.</li>
<li>Any critical value(s) is informed to the patient by sms (if mobile number available) immediately upon testing the sample.</li>
<li>Constant effort is made to maintain a turnaround time of maximum 2 hours between sample received by the lab and report generation in routine tests.</li>
<li>The bone marrow procedure is done by pathologists themselves in the laboratory. The procedure can also be performed bed-side in debilitated hospitalized patients on request.</li>
<li>Bone marrow aspiration slides (when procedure performed by clinicians) are also accepted for evaluation.</li>
<li>The bone marrow aspiration reports are provided to the patients/clinicians on the same day (for procedures performed between 8AM and 5 PM).</li>
<li>Slides are also accepted for second opinion</li>
</ul>

    </div>
  </div>

                </div>
            </div>
    </div>
</section>


      
      <div id="new_comment">
              <div class="new_comment">
                    </div>
            </div>

    </div>
<!--    << END ========================= MAIN COLUMN ========================  -->









@include('maitridiagnosticlab/sidebar')




</div>
</div>
</section>
<!--    << END ========================= CONTENT AREA ========================  -->
</div>




@endsection